version: '3.9'

services:
  hugo-onepager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hugo-onepager
    restart: unless-stopped
    mem_limit: 64m
    mem_reservation: 16m
    cpus: 0.1
    networks:
      - t2_proxy
    labels:
      # Traefik aktivieren
      - "traefik.enable=true"
      - "com.centurylinklabs.watchtower.enable=false"
      
      # HTTP Router
      - "traefik.http.routers.hugo-onepager.rule=Host(`max-it.tech`)"
      - "traefik.http.routers.hugo-onepager.entrypoints=https"
      - "traefik.http.routers.hugo-onepager.tls=true"
      - "traefik.http.routers.hugo-onepager.tls.certresolver=dns-cloudflare"
      
      # Middlewares
      - "traefik.http.routers.hugo-onepager.middlewares=chain-no-auth@file"
      
      # Service Definition
      - "traefik.http.services.hugo-onepager.loadbalancer.server.port=80"

networks:
  t2_proxy:
    external: true
